version: '3'

services:
  app:
    build: .
    environment:
      AUTORELOAD_PROGRAMS: "swoole swoole2"
      AUTORELOAD_ANY_FILES: 1
    ports:
      - "0.0.0.0:80:9501"
      - "0.0.0.0:9502:9502"
      - "0.0.0.0:9501:9501"
#    tty: true
#    stdin_open: true
    volumes:
      - ./rootfilesystem/var/www:/var/www