version: '3'

services:
  app:
    build: .
    environment:
      AUTORELOAD_PROGRAMS: "swoole checker"
      AUTORELOAD_ANY_FILES: 1
    ports:
      - "0.0.0.0:9555:9555"
    #    tty: true
    #    stdin_open: true
    volumes:
      - ./rootfilesystem/var/www:/var/www